# Generated by Django 5.1.5 on 2025-01-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temp_field',
            field=models.CharField(default='', max_length=1),
        ),
    ]
