# Generated by Django 5.1.5 on 2025-01-19 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='temp_field',
        ),
    ]
