# Generated by Django 5.1 on 2025-01-19 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('photo', models.FileField(upload_to='portfolio_photos/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('experience_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior')], default='BEGINNER', max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
                ('specialisations', models.ManyToManyField(related_name='portfolios', to='portfolio.specialisation')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_method', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('LINKEDIN', 'LinkedIn')], default='EMAIL', max_length=20)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_preferences', to='portfolio.portfolio')),
            ],
        ),
    ]
