# Generated by Django 5.1 on 2025-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialisation',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('ReactJs', 'ReactJs')], default='Python', max_length=50, unique=True),
        ),
    ]
