# Generated by Django 5.1 on 2025-01-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialisation',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('ReactJs', 'ReactJs'), ('Html/css', 'Html/css'), ('Java', 'Java'), ('Csharp', 'Csharp'), ('Javascript', 'Javascript')], default='Python', max_length=50, unique=True),
        ),
    ]
