# Generated by Django 5.1.5 on 2025-01-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_specialisation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='portfolio.topic'),
        ),
    ]
