# Generated by Django 5.1.5 on 2025-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_topic_portfolio_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('AI', 'AI'), ('Frontend', 'Frontend'), ('Taylor Swift', 'Taylor Swift')], max_length=50, unique=True),
        ),
    ]
