# Generated by Django 5.1 on 2025-01-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_contactpreferences_preferred_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='profile_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
