# Generated by Django 5.1 on 2025-01-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_topic_name'),
        ('portfolio', '0007_rename_profile_name_portfolio_first_name_and_more'),
    ]

    operations = [
    ]
