# Generated by Django 5.1.5 on 2025-01-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_merge_20250128_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(null=True, upload_to='portfolio/'),
        ),
    ]
