# Generated by Django 5.1.5 on 2025-01-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_populate_choice_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='specialisations_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='topic_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
