# Generated by Django 5.1.5 on 2025-01-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_portfolio_company_portfolio_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
