# Generated by Django 5.1 on 2025-01-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
