# Generated by Django 5.1 on 2025-01-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(choices=[('Brisbane', 'Brisbane'), ('Sydney', 'Sydney'), ('Perth', 'Perth'), ('Melbourne', 'Melbourne'), ('Adelaide', 'Adelaide'), ('Darwin', 'Darwin'), ('Canberra', 'Canberra'), ('Gold Coast', 'Gold Coast')], default='Brisbane', max_length=50, unique=True)),
            ],
        ),
    ]
